ticket:
  csvFilePath: /Users/alexanderbuob/IdeaProjects/ticket-api/src/main/csv/sampleTickets.csv
spring:
  h2:
    console:
      enabled: true
      path: /console
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: none
server:
  port: 8181
